version: "3.8"
services:
  job_portal:
    build:
      context: .
      dockerfile: Dockerfile # The Dockerfile in the root directory
    ports:
      - "8000:8000" # Backend API port
    env_file:
      - ./backend/.env # Backend environment variables
    volumes:
      - ./backend:/backend # Only mount the backend folder
      - ./frontend:/frontend # Only mount the frontend folder if needed # Optional: Mounts the entire project into the container
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # MongoDB port
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
